---
# roles/lair-docker/tasks/create-passwords.yml

- name: Build Random Password
  set_fact:
      vault_lair_password: '{{ lookup("password", "/dev/null length=20 chars=ascii_letters,digits,punctuation") }}'


