---
# roles/lair-docker/tasks/main.yml

- name: check if vault file exists
  delegate_to: 127.0.0.1
  become: no
  delegate_facts: True
  stat: 
    path: '{{ role_path }}/vars/vault.yml'
  register: vault_lair_file
  tags:
    - lair-docker

- name: Include Vault Vars
  include_vars: "vault.yml"
  when: (vault_lair_file.stat.exists == true)
  tags:
    - lair-docker

- name: Create Passwords
  include: create-passwords.yml
  when: (vault_lair_file.stat.exists == false)
  tags:
    - lair-docker
    - lair-docker:create-passwords

- name: Create Vault
  include: create-vault.yml
  when: (vault_lair_file.stat.exists == false)
  tags:
    - lair-docker
    - lair-docker:vault

- name: Create DNS Entry
  include: create-dns.yml
  tags:
     - lair-docker
     - lair-docker:dns

- name: Create Continer
  include: create-container.yml
  tags:
     - lair-docker
     - lair-docker:container

- name: Destroy Container
  include: destroy-container.yml
  tags:
    - never
    - lair-docker:destroy

- name: Destroy DNS
  include: destroy-dns.yml
  tags:
    - never
    - destroy-all
    - lair-docker:destroy

- name: Destroy vault
  include: destroy-vault.yml
  tags:
    - never
    - destroy-all
    - lair-docker:destroy
