---
- name: check if ssh file exists
  stat: 
    path: "{{ playbook_dir }}/files/ssh/ssh-key"
  register: ssh_file

- name: delete ec2 key pair on AWS
  ec2_key:
    name: "{{ keypair }}"
    state: absent

- name: delete ec2 key pair on disk
  file:
    state: absent
    path: "{{ playbook_dir }}/files/ssh/ssh-key"
  when: (ssh_file.stat.exists == true)