---
- name: Ensures portainer dir exists
  file:
    path: "{{ portainer_dir }}"
    state: directory

- name: Adding password file
  template:
    src: portainer_password.j2
    dest: "{{ portainer_dir }}/portainer_password.txt"
    mode: 0600

- name: Portainer
  docker_container:
    name: portainer
    image: portainer/portainer:latest
    hostname: portainer
    state: started
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    command: '--admin-password-file /tmp/portainer_password.txt'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ portainer_dir }}/data:/data"
      - "{{ portainer_dir }}/portainer_password.txt:/tmp/portainer_password.txt"
    networks:
      - name: "{{ docker_network }}"
    labels:
      traefik.docker.network: "{{ docker_network }}"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:{{ portainer_hostname }}.{{ route53_domian_name }}"
      traefik.frontend.whiteList.sourceRange: "{{ traefik_allowed_ips }}"
      traefik.basic.port: "9000"