---
# roles/portainer-docker/tasks/destroy-container.yml

- name: Destroy traefik dir exists
  file:
    path: '{{ item }}'
    state: absent
  with_items:
  - '{{ portainer_dir }}'

- name: Destroy Portainer
  docker_container:
    name: portainer
    state: absent
