- name: check if vault file exists
  delegate_to: 127.0.0.1
  become: no
  delegate_facts: True
  stat: 
    path: '{{ role_path }}/vars/vault.yml'
  register: vault_portainer_file
  tags:
    - portainer-docker

- name: Include Vault Vars
  include_vars: "vault.yml"
  when: (vault_portainer_file.stat.exists == true)
  tags:
    - portainer-docker

- name: Create Passwords
  include: create-passwords.yml
  when: (vault_portainer_file.stat.exists == false)
  tags:
    - portainer-docker
    - portainer-docker:create-passwords

- name: Create Vault
  include: create-vault.yml
  when: (vault_portainer_file.stat.exists == false)
  tags:
    - portainer-docker
    - portainer-docker:vault-write

- name: Create DNS Entry
  include: create-dns.yml
  tags:
     - portainer-docker
     - portainer-docker:dns

- name: Create Container
  include: create-container.yml
  tags:
     - portainer-docker
     - portainer-docker:create

- name: Destroy Container
  include: destroy-container.yml
  tags:
    - never
    - portainer-docker:destroy

- name: Destroy DNS
  include: destroy-dns.yml
  tags:
    - never
    - destroy-all
    - portainer-docker:destroy

- name: Destroy vault
  include: destroy-vault.yml
  tags:
    - never
    - destroy-all
    - portainer-docker:destroy