---
# tasks file for aws-sg

- name: Destroy security groups
  delegate_to: localhost
  become: no
  delegate_facts: True
  ec2_group:
    name: "{{ security_group_name }}"
    description: "Security group for the {{ security_group_name }}"
    vpc_id: "{{ vpc_net_facts.vpcs[0].id }}"
    region: "{{ aws_region }}"
    state: "absent"
  when: vpc_net_facts.vpcs[0] is defined
