---
- name: Create Container
  include: create-container.yml
  tags:
     - watchtower-docker
     - watchtower-docker:create

- name: Destroy Container
  include: destroy-container.yml
  tags:
    - never
    - watchtower-docker:destroy