---
# roles/backup-docker/tasks/create-passwords.yml

- name: Create Random Password
  set_fact:
      vault_borg_encrypt_password: '{{ lookup("password", "/dev/null length=30 chars=ascii_letters,digits") }}'

- name: Create Random Password
  delegate_to: 127.0.0.1
  become: no
  delegate_facts: True
  command: 'pwgen -cnyB 20 1'
  register: vault_s3backup_user_password