---
# roles/backup-docker/tasks/create-s3.yml

- name: Create an empty bucket
  delegate_to: localhost
  become: no
  delegate_facts: True
  aws_s3:
    bucket: '{{ s3_bucket_name }}'
    mode: create
    object: '{{ s3_backup_dir }}'
    permission: private