---
# roles/backup-docker/tasks/main.yml

- name: check if vault file exists
  delegate_to: 127.0.0.1
  become: no
  delegate_facts: True
  stat: 
    path: '{{ role_path }}/vars/vault.yml'
  register: vault_backup_file
  tags:
    - backup-docker

- name: Include Vault Vars
  include_vars: "vault.yml"
  when: (vault_backup_file.stat.exists == true)
  tags:
    - backup-docker

- name: Create Passwords
  include: create-passwords.yml
  when: (vault_backup_file.stat.exists == false)
  tags:
    - backup-docker
    - backup-docker:passwords

- name: Create IAM accounts
  include: create-iam.yml
  tags:
    - backup-docker
    - backup-docker:iam

- name: Create Vault
  include: create-vault.yml
  when: (vault_backup_file.stat.exists == false)
  tags:
    - backup-docker
    - backup-docker:vault-write

- name: Create S3 Bucket
  include: create-s3.yml
  tags:
     - backup-docker
     - backup-docker:s3-bucket

- name: Create Continer
  include: create-container.yml
  tags:
     - backup-docker
     - backup-docker:container

- name: Destroy Container
  include: destroy-container.yml
  tags:
    - never
    - backup-docker:destroy

- name: Destroy IAM
  include: destroy-iam.yml
  tags:
    - never
    - destroy-all
    - backup-docker:destroy
 
- name: Destroy S3
  include: destroy-s3.yml
  tags:
    - never
    - destroy-all
    - backup-docker:destroy

- name: Destroy vault
  include: destroy-vault.yml
  tags:
    - never
    - destroy-all
    - backup-docker:destroy