---
# roles/traefik-docker/tasks/destroy-container.yml

- name: Destroy traefik dir exists
  file:
    path: '{{ item }}'
    state: absent
  with_items:
  - '{{ traefik_dir }}'

- name: Destroy Cobaltstrike
  docker_container:
    name: traefik
    state: absent
