---
# roles/traefik-docker/tasks/main.yml

- name: check if vault file exists
  delegate_to: 127.0.0.1
  become: no
  delegate_facts: True
  stat: 
    path: '{{ role_path }}/vars/vault.yml'
  register: vault_traefik_file
  tags:
    - traefik-docker

- name: Include Vault Vars
  include_vars: "vault.yml"
  when: (vault_traefik_file.stat.exists == true)
  tags:
    - traefik-docker

- name: Create Passwords
  include: create-passwords.yml
  when: (vault_traefik_file.stat.exists == false)
  tags:
    - traefik-docker
    - traefik-docker:create-passwords

- name: Create Security Group
  include: create-sg.yml
  tags:
    - traefik-docker
    - traefik-docker:sg

- name: Create IAM accounts
  include: create-iam.yml
  tags:
    - traefik-docker
    - traefik-docker:iam

- name: Write Vault
  include: create-vault.yml
  when: (vault_traefik_file.stat.exists == false)
  tags:
    - traefik-docker
    - traefik-docker:vault

- name: Create DNS Entry
  include: create-dns.yml
  tags:
     - traefik-docker
     - traefik-docker:dns

- name: Create Continer
  include: create-container.yml
  tags:
     - traefik-docker
     - traefik-docker:create

- name: Destroy Container
  include: destroy-container.yml
  tags:
    - never
    - traefik-docker:destroy

- name: Destroy DNS
  include: destroy-dns.yml
  tags:
    - never
    - destroy-all
    - traefik-docker:destroy

- name: Destroy IAM
  include: destroy-iam.yml
  tags:
    - never
    - destroy-all
    - traefik-docker:destroy

- name: Destroy vault
  include: destroy-vault.yml
  tags:
    - never
    - destroy-all
    - traefik-docker:destroy

