---

- name: Gather VPC Facts
  ec2_vpc_net_facts:
    filters:
      "tag:Name": '{{ vpc_name }}'
  register: vpc_facts

- name: Remove route table
  ec2_vpc_route_table:
    state: "absent"
    vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
    region: "{{ aws_region }}"
    tags:
      Name: "Public"
  when: vpc_facts.vpcs[0] is defined

- name: Remove Internet Gateway for VPC
  ec2_vpc_igw:
    vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
    region: "{{ aws_region }}"
    state: "absent"
  when: vpc_facts.vpcs[0] is defined

- name: Remove Public Subnet
  ec2_vpc_subnet:
    state: "absent"
    vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
    cidr: "{{ public_subnet_1_cidr }}"
    az: "{{ aws_region }}a"
    region: "{{ aws_region }}"
    resource_tags:
      Name: "Public Subnet"
  when: vpc_facts.vpcs[0] is defined

- name: Remove VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
    state: "absent"
  when: vpc_facts.vpcs[0] is defined