---
# roles/aws-ec2/tasks/create.yml

- name: Start the EC2 instance
  ec2:
    region: "{{ aws_region }}"
    keypair: "{{ keypair }}"
    group: "{{ security_group_name }}"
    image: "{{ ami_facts.images[0].image_id }}"
    instance_type: "{{ instance_type }}"
    instance_tags:
      Name: "{{ instance_name }}"
    volumes: "{{ volumes }}"
    wait: yes
    vpc_subnet_id: "{{ vpc_subnet_facts.subnets[0].id }}"
    count_tag:
      Name: "{{ instance_name }}"
    exact_count: 1
  register: ec2

- name: Gather hosts matching tags
  ec2_instance_facts:
    filters:
      instance-state-name: running
      "tag:Name": "{{ instance_name }}"
    region: "{{ aws_region }}"
  register: current_instance

- name: Wait for instance to boot
  wait_for:
    host: "{{ current_instance.instances[0].public_dns_name }}"
    port: 22
    delay: 10
    timeout: 300
    state: started