---
# roles/aws-ec2/tasks/destroy.ym
- name: Gather hosts matching tags. This is important.
  ec2_instance_facts:
    filters:
      instance-state-name: running
      "tag:Name": "{{ instance_name }}"
    region: "{{ region }}"
  register: current_instance


- name: Terminate instances that were previously launched
  ec2:
    state: 'absent'
    instance_ids: '{{ current_instance.instances[0].instance_id }}'
