---
# roles/aws-ec2/tasks/destroy.ym
- name: Gather hosts matching tags.
  ec2_instance_facts:
    filters:
      instance-state-name: running
      "tag:Name": "{{ instance_name }}"
    region: "{{ aws_region }}"
  register: current_instance


- name: Terminate instances that were previously launched
  ec2:
    state: 'absent'
    instance_ids: '{{ current_instance.instances[0].instance_id }}'
    region: "{{ aws_region }}"
    wait: True
  when: 'current_instance.instances[0] is defined'
