---
# roles/cobaltstrike-docker/tasks/create-dns.yml

- name: Add DNS Records
  delegate_to: 127.0.0.1
  become: no
  delegate_facts: True
  route53:
      state: present
      zone: "{{ item.zone }}"
      record: "{{ item.record }}"
      type: A
      ttl: 7200
      value: "{{ item.value}}"
      overwrite: True
      wait: yes
  with_items:
    - zone: "{{ route53_domian_name }}"
      record: "{{ cs_hostname }}.{{ route53_domian_name }}"
      value: "{{ current_instance.instances[0].public_ip_address }}"