---
# roles/cobaltstrike-docker/tasks/create-passwords.yml

- name: Create Random Password
  set_fact:
      vault_cs_password: '{{ lookup("password", "/dev/null length=20 chars=ascii_letters,digits,punctuation") }}'


