---
# roles/cobaltstrike-docker/tasks/main.yml

- name: check if vault file exists
  delegate_to: 127.0.0.1
  become: no
  delegate_facts: True
  stat: 
    path: '{{ role_path }}/vars/vault.yml'
  register: vault_cobaltstrike_file
  tags:
    - cobaltstrike-docker

- name: Include Vault Vars
  include_vars: "vault.yml"
  when: (vault_cobaltstrike_file.stat.exists == true)
  tags:
    - cobaltstrike-docker

- meta: end_play
  when: (vault_cs_key is not defined)
  tags:
    - cobaltstrike-docker
    - cobaltstrike-docker:check-license

- name: Create Passwords
  include: create-passwords.yml
  when: (vault_cobaltstrike_file.stat.exists == false)
  tags:
    - cobaltstrike-docker
    - cobaltstrike-docker:passwords

- name: Create Security Group
  include: create-sg.yml
  tags:
    - cobaltstrike-docker
    - cobaltstrike-docker:sg

- name: Create Vault
  include: create-vault.yml
  when: (vault_cobaltstrike_file.stat.exists == false)
  tags:
    - cobaltstrike-docker
    - cobaltstrike-docker:vault

- name: Create DNS Entry
  include: create-dns.yml
  tags:
     - cobaltstrike-docker
     - cobaltstrike-docker:dns

- name: Create Continer
  include: create-container.yml
  tags:
     - cobaltstrike-docker
     - cobaltstrike-docker:container

- name: Destroy Container
  include: destroy-container.yml
  tags:
    - never
    - cobaltstrike-docker:destroy

- name: Destroy DNS
  include: destroy-dns.yml
  tags:
    - never
    - destroy-all
    - cobaltstrike-docker:destroy

- name: Destroy vault
  include: destroy-vault.yml
  tags:
    - never
    - destroy-all
    - cobaltstrike-docker:destroy