---
- name: Creating users
  user: 
    name: "{{ item.name }}"
    groups: "{{ item.groups}} "
    append: "{{ item.append}}"
    state: present
    createhome: "{{ item.createhome }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell }}"
  with_items:
    - { name: "{{ netdata_user }}", groups: "docker", append: yes, createhome: no, uid: "{{ netdata_uid }}", shell: "/sbin/nologin" }

- name: Netdata
  docker_container:
    name: netdata
    image: firehol/netdata:latest
    pull: yes
    state: started
    hostname: netdata
    restart_policy: on-failure
    restart_retries: 2
    capabilities: "SYS_PTRACE"
    env:
      PUID: "{{ netdata_uid }}"
      PGID: 989 # Docker GID for socket permissions
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - name: "{{ docker_network }}"
    labels:
      traefik.docker.network: "{{ docker_network }}"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:metrics.{{ route53_domian_name }}"
      traefik.frontend.whiteList.sourceRange: "{{ traefik_allowed_ips }}"
      traefik.frontend.auth.basic.users: "{{ metrics_basicauth_user }}:{{ vault_metrics_basicauth_password | password_hash('blowfish') }}"
      traefik.basic.port: "19999"