---
# roles/netdata-docker/tasks/main.yml
- name: check if vault file exists
  delegate_to: 127.0.0.1
  become: no
  delegate_facts: True
  stat: 
    path: '{{ role_path }}/vars/vault.yml'
  register: vault_netdata_file
  tags:
    - netdata-docker

- name: Include Vault Vars
  include_vars: "vault.yml"
  when: (vault_netdata_file.stat.exists == true)
  tags:
    - netdata-docker

- name: Create Passwords
  include: create-passwords.yml
  when: (vault_netdata_file.stat.exists == false)
  tags:
    - netdata-docker
    - netdata-docker:create-passwords

- name: Write Vault
  include: create-vault.yml
  when: (vault_netdata_file.stat.exists == false)
  tags:
    - netdata-docker
    - netdata-docker:create-vault

- name: Create DNS Entry
  include: create-dns.yml
  tags:
     - netdata-docker
     - netdata-docker:dns

- name: Create Continer
  include: create-container.yml
  tags:
     - netdata-docker
     - netdata-docker:create

- name: Destroy Container
  include: destroy-container.yml
  tags:
    - never
    - netdata-docker:destroy

- name: Destroy DNS
  include: destroy-dns.yml
  tags:
    - never
    - destroy-all
    - netdata-docker:destroy

- name: Destroy vault
  include: destroy-vault.yml
  tags:
    - never
    - destroy-all
    - netdata-docker:destroy